### ISSUE TITLE
Use docstrings for documenting functions

### ISSUE THREAD

**Issue by alchemyst** [CR34M3/Optimised_MPC_constraints__Code#2]
Python includes documentation functions that work for instance when you run "help function" in ipython.  Check http://www.python.org/dev/peps/pep-0257/ for the docstring conventions.  Using these conventions means that automated tools can be used to generate documentation.  It is also required for things like doctest to work (as doctest scans the docstrings).  You can even use reStructuredText as in http://www.python.org/dev/peps/pep-0012/

**Comment by CR34M3** [comment]
- Added docstrings to all modules.
- Doctest implementation in progress
