### ISSUE TITLE
Follow PEP8

### ISSUE THREAD

**Issue by alchemyst** [CR34M3/Optimised_MPC_constraints__Code#8]
Guido has [spoken](http://www.python.org/dev/peps/pep-0008/), and we must obey.

Try running [pep8.py](http://pypi.python.org/pypi/pep8) on the code, or just enable the [pylint support in pydev](http://pydev.org/manual_adv_code_analysis.html).

**Comment by CR34M3** [comment]
Done.
Code now PEP8 compliant (mostly).
